### ISSUE TITLE
None of the links to the Face Antispoofing Datasets are valid.

### ISSUE THREAD

**Issue by neoludd8** [ZhaoJ9014/face.evoLVe.PyTorch#124]
I'm on a deadline and i need a descent face anti-spoofing dataset such as Replay-Attack or Casia-FASD. However, none of the links to these datasets are working. Any help?

**Comment by xsacha** [comment]
I have the same issue. Message me if you get access.
My Baidu accounts no longer work because they require a local China phone number -- even ones I have signed up for with a phone number in the past. If I register a new account, I receive the message:
暂不支持海外及港澳台地区注册 (Essentially, overseas accounts are not allowed)

**Comment by neoludd8** [comment]
It turned out to be an IP address issue, using a VPN solved my problem.

**Comment by Morceguito** [comment]
I am working on my thesis and I'm looking for Replay Attack and OULU datasets, could you share where I would get access to them?
