### ISSUE TITLE
expect publishing which based tensorflow framework

### ISSUE THREAD

**Issue by berli** [ZhaoJ9014/face.evoLVe.PyTorch#14]

**Comment by ZhaoJ9014** [comment]
Thank you for your suggestion. Assigning and building graphs on PyTorch follows a dynamic computation graphical approach. Users who are familiar with mathematical libraries in Python will find it easy, since one does not have to scratch their head to build the graphs. You can directly write the input and output functions the way you want, without worrying about dimensional tensors. With the CUDA support, this makes much easier and more flexible for researchers/engineers to develop high-performance deep face recognition models and algorithms quickly for practical use and deployment. Whereas in TensorFlow, one has to work on building the dimensions of the tensor (graph) as well as assigning the placeholders for the variables. Once this is completed, a session has to be run in order to work out all the computations. However, we will still consider it:)

**Comment by clhne** [comment]
@ZhaoJ9014 
First, thank you for NUS-Panasonic's great job!
As to dynamic computation graphical approach of Tensorflow, just try  [Eager Execution](https://medium.com/coding-blocks/eager-execution-in-tensorflow-a-more-pythonic-way-of-building-models-e461810618c8)  and [Tensorflow Fold](https://medium.com/@maheshwar.ligade/dynamic-computation-graphs-dcg-with-tensorflow-fold-33638b2d5754) :)
Another similar question:
Could you explain in detail why not use MxNet framework(ArcFace source code)? 
Thanks.
