### ISSUE TITLE
Question about MegaFace results

### ISSUE THREAD

**Issue by lymanblue** [ZhaoJ9014/face.evoLVe.PyTorch#17]
Hi~

Thank you for your great work!
We wonder the validation results (or code) for MegaFace would be reported or not.

Thank you.

**Comment by clhne** [comment]
I think the author may not have time to val it on Megaface, because of the megaface big size, preprocessing may use a lot of time :)
If you want know the results, you could download the [pre-trained model](https://github.com/ZhaoJ9014/face.evoLVe.PyTorch#model-zoo) and rewrite the evaluation code for megaface.
There is another workaround, reuse [ArcFace's Megaface evaluation](https://github.com/deepinsight/insightface/tree/master/Evaluation/Megaface).
Finally, I use r100-ii network to retrain arcface, and add some new tricks, the results as follows:
![image](https://user-images.githubusercontent.com/11884005/53539314-0f320380-3b4c-11e9-84e3-57c3f21d1ef3.png)

**Comment by ZhaoJ9014** [comment]
Thank you for your question. Yes, we are considering it and may release in near future.
