### ISSUE TITLE
About the model of MTCNN

### ISSUE THREAD

**Issue by PuNeal** [ZhaoJ9014/face.evoLVe.PyTorch#18]
Hello,
Thanks for your great work!!! My question is that what is the difference of  the MTCNN  model provided in this repo between the original model released by the auther. Do you retrain this model on your own dataset? Thanks!

**Comment by ZhaoJ9014** [comment]
Thank you for your question. Currently, we did not include the training process due to a common issue that the re-implementations can hardly reproduce the results reported by the MTCNN original paper. We thus choose to transfer the weights and implement the inference process. Please kindly inform us if you get any new results by reproducing the reported results with self-training in the future.
