### ISSUE TITLE
About some problems in evaluation 

### ISSUE THREAD

**Issue by luzai** [ZhaoJ9014/face.evoLVe.PyTorch#36]
Thank you for your great repo! May ask some problems about evaluation?
- The model is trained by `RGB` image, but evaluated with `BGR` image, which cause slight performance degradation, to be specific, acc on cfp_fp can reach 98% if fix this problem. 
- May I ask why you use `ccrop`, first resize 112x112 to 128x128 and then crop to 112x112? 
- What is the difference with the validation dataset released by InsightFace_Pytorch? I notice that using your released cfp_fp can yield a better accuracy.

**Comment by ZhaoJ9014** [comment]
> Thank you for your great repo! May ask some problems about evaluation?
> 
> * The model is trained by `RGB` image, but evaluated with `BGR` image, which cause slight performance degradation, to be specific, acc on cfp_fp can reach 98% if fix this problem.
> * May I ask why you use `ccrop`, first resize 112x112 to 128x128 and then crop to 112x112?
> * What is the difference with the validation dataset released by InsightFace_Pytorch? I notice that using your released cfp_fp can yield a better accuracy.

Thank you very much. We have updated the code and performance accordingly. 
We use center crop during testing because during training we adopted random crop data augmentation. 
The data is exactly the same with those used by InsightFace_Pytorch. Our performance is better thanks to the highly effective and efficient face.evoLVe framework:)

**Comment by luzai** [comment]
It is quite great to improve 92.74 to 98.14 on cfp_fp compared to insightface! Thanks to sharing the highly effective and efficient face.evoLVe framework:)
