### ISSUE TITLE
Where the MTCNN parameters are from?

### ISSUE THREAD

**Issue by Yououko** [ZhaoJ9014/face.evoLVe.PyTorch#9]
Thanks for your job.
Did you train MTCNN parameters `p/o/rnet.npy` by yourself or use the parameters from other places? I'd like to know how it was trained.

**Comment by ZhaoJ9014** [comment]
Thank you for your question. Currently, we did not include the training process due to a common issue that the re-implementations can hardly reproduce the results reported by the MTCNN original paper. We thus choose to transfer the weights and implement the inference process. Please kindly inform us if you get any new results by reproducing the reported results with self-training in the future.

**Comment by Yououko** [comment]
Thanks for your quick reply.
Did you transfer the weights from the author's repository https://github.com/kpzhang93/MTCNN_face_detection_alignment/tree/master/code/codes/MTCNNv2/model ?
